[toolchain]
channel = "nightly-2024-08-05"
# channel = "nightly-2024-08-01"
# channel = "nightly-2024-07-20"
# channel = "nightly-2024-07-08"
# channel = "nightly-2024-06-20"
# channel = "nightly-2023-10-18"
components = ["rust-src", "rust-analyzer"]